<?php
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Laporan extends CI_Controller {
    function __construct() {
        parent::__construct();
        is_logged_in();
        $this->load->helper('ata');
		$this->load->helper('tglindo');
		$this->load->helper('rupiah');
		$this->load->model('Admin_model', 'admin');
		$this->load->model('User_model', 'user');
        $this->load->model('Alternatif_model');
        $this->load->model('Kriteria_model');
        $this->load->model('Subkriteria_model');
		$this->load->model('Penilaian_model');
    }

    /*
    * Listing of alternatif
    */
    public function index() 
    {
            $id_user = $this->session->userdata('id_user');
            $level = $this->session->userdata('level');
            $data['level_akses'] = $level;
            $data['title'] = 'Detail Laporan Penilaian';
            $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
            $data['list_user'] = $this->db->get('mst_user')->result_array();
            $data['identitas'] = $this->db->get('tbl_aplikasi')->result();
            $data['alternatif'] = $this->Alternatif_model->get_all_alternatif();
            $data['kriteria'] = $this->Kriteria_model->get_all_kriteria();
            $data['penilaian'] = $this->Penilaian_model->get_all_penilaian_report();
            
            $data['all_alternatif_filled'] = $this->Penilaian_model->is_all_alternatif_filled();
            $current_year = date('Y'); // Mendapatkan tahun saat ini
            $data['penilaian_exist'] = $this->Penilaian_model->CekPenilaianExist($current_year);
            $data['cek_header_saw'] = $this->Penilaian_model->CekHeaderSaw($current_year);
            $data['cek_header_smart'] = $this->Penilaian_model->CekHeaderSmart($current_year);
            $data['cek_preview'] = $this->Penilaian_model->CekPreview($current_year);
            $data['cek_preview_smart'] = $this->Penilaian_model->CekPreviewSmart($current_year);
            $data['min_max_saw'] = $this->Penilaian_model->get_min_max_saw();
            $data['min_max_smart'] = $this->Penilaian_model->get_min_max_smart();
            $data['tahun'] = $current_year;
            // var_dump($data['min_max_saw']);
            // var_dump($data['min_max_smart']);
            // die();
            $this->load->view('templates/header', $data);
            if($level == 'Admin'){
                $this->load->view('templates/sidebar_admin', $data);
            }elseif($level == 'Perbekel'){
                $this->load->view('templates/sidebar_perbekel', $data);
            }
            $this->load->view('laporan/index', $data);
            $this->load->view('templates/footer');
    }
    public function detail_perhitungan()
    {
         $id_user = $this->session->userdata('id_user');
            $level = $this->session->userdata('level');
            $data['title'] = 'Metode SAW';
            $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
            $data['list_user'] = $this->db->get('mst_user')->result_array();
            $data['identitas'] = $this->db->get('tbl_aplikasi')->result();
            $data['alternatif'] = $this->Alternatif_model->get_all_alternatif();
            $data['kriteria'] = $this->Kriteria_model->get_all_kriteria();
            $data['penilaian'] = $this->Penilaian_model->get_all_penilaian_report();

            $data['all_alternatif_filled'] = $this->Penilaian_model->is_all_alternatif_filled();
            $current_year = date('Y'); // Mendapatkan tahun saat ini
            $data['penilaian_exist'] = $this->Penilaian_model->CekPenilaianExist($current_year);
            $data['cek_header_saw'] = $this->Penilaian_model->CekHeaderSaw($current_year);
            $data['cek_header_smart'] = $this->Penilaian_model->CekHeaderSmart($current_year);
            $data['cek_preview'] = $this->Penilaian_model->CekPreview($current_year);
            $data['cek_preview_smart'] = $this->Penilaian_model->CekPreviewSmart($current_year);
            $data['min_max_saw'] = $this->Penilaian_model->get_min_max_saw();
            $data['min_max_smart'] = $this->Penilaian_model->get_min_max_smart();
            $data['tahun'] = $current_year;
            $this->load->view('templates/header', $data);
            if($level == 'Admin'){
                $this->load->view('templates/sidebar_admin', $data);
            }elseif($level == 'Perbekel'){
                $this->load->view('templates/sidebar_perbekel', $data);
            }
            $this->load->view('laporan/detail_perhitungan', $data);
            $this->load->view('templates/footer');
    }

    public function filter_tahun()
    {
            $id_user = $this->session->userdata('id_user');
            $level = $this->session->userdata('level');
            $data['title'] = 'Metode SAW';
            $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
            $data['list_user'] = $this->db->get('mst_user')->result_array();
            $data['identitas'] = $this->db->get('tbl_aplikasi')->result(); 
            $current_year = $this->input->post('tahun');
            
            $data['tahun'] = $current_year;
            $data['alternatif'] = $this->Alternatif_model->get_all_alternatif();
            $data['kriteria'] = $this->Kriteria_model->get_all_kriteria();
            $data['penilaian'] = $this->Penilaian_model->filter_get_all_penilaian_report($current_year);
            $data['cek_header_saw'] = $this->Penilaian_model->CekHeaderSaw($current_year);
            $data['cek_header_smart'] = $this->Penilaian_model->CekHeaderSmart($current_year);
            $data['cek_preview'] = $this->Penilaian_model->CekPreview($current_year);
            $data['cek_preview_smart'] = $this->Penilaian_model->CekPreviewSmart($current_year);
            $data['min_max_saw'] = $this->Penilaian_model->get_min_max_saw();
            $data['min_max_smart'] = $this->Penilaian_model->get_min_max_smart();
            $this->load->view('templates/header', $data);
            if($level == 'Admin'){
                $this->load->view('templates/sidebar_admin', $data);
            }elseif($level == 'Perbekel'){
                $this->load->view('templates/sidebar_perbekel', $data);
            }
            $this->load->view('laporan/filter_tahun', $data);
            $this->load->view('templates/footer');
    }

    public function cetak($tahun)
    {
            $id_user = $this->session->userdata('id_user');
            $level = $this->session->userdata('level');
            $data['title'] = 'Cetak Penilaian';
            $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
            $data['list_user'] = $this->db->get('mst_user')->result_array();
            $data['identitas'] = $this->db->get('tbl_aplikasi')->result();
            $current_year = $tahun;
            
            $data['tahun'] = $current_year;
            $data['alternatif'] = $this->Alternatif_model->get_all_alternatif();
            $data['kriteria'] = $this->Kriteria_model->get_all_kriteria();
            $data['penilaian'] = $this->Penilaian_model->filter_get_all_penilaian_report($current_year);

            $data['all_alternatif_filled'] = $this->Penilaian_model->is_all_alternatif_filled();
            $current_year = date('Y'); // Mendapatkan tahun saat ini
            $data['penilaian_exist'] = $this->Penilaian_model->CekPenilaianExist($current_year);
            $data['cek_header_saw'] = $this->Penilaian_model->CekHeaderSaw($current_year);
            $data['cek_header_smart'] = $this->Penilaian_model->CekHeaderSmart($current_year);
            $data['cek_preview'] = $this->Penilaian_model->CekPreview($current_year);
            $data['cek_preview_smart'] = $this->Penilaian_model->CekPreviewSmart($current_year);
            $data['min_max_saw'] = $this->Penilaian_model->get_min_max_saw();
            $data['min_max_smart'] = $this->Penilaian_model->get_min_max_smart();
            $data['tahun'] = $current_year;
            
            $this->load->view('laporan/cetak', $data);
            
    }

    public function cetak_filter($tahun)
    {
            $id_user = $this->session->userdata('id_user');
            $level = $this->session->userdata('level');
            $data['title'] = 'Cetak Penilaian';
            $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
            $data['list_user'] = $this->db->get('mst_user')->result_array();
            $data['identitas'] = $this->db->get('tbl_aplikasi')->result(); 
            $current_year = $tahun;
            $data['alternatif'] = $this->Alternatif_model->get_all_alternatif();
            $data['kriteria'] = $this->Kriteria_model->get_all_kriteria();
            $data['penilaian'] = $this->Penilaian_model->filter_get_all_penilaian_report($current_year);
            $data['cek_header_saw'] = $this->Penilaian_model->CekHeaderSaw($current_year);
            $data['cek_header_smart'] = $this->Penilaian_model->CekHeaderSmart($current_year);
            $data['min_max_saw'] = $this->Penilaian_model->get_min_max_saw();
            $data['min_max_smart'] = $this->Penilaian_model->get_min_max_smart();
            $this->load->view('laporan/cetak', $data);
    }
}