<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Subkriteria extends CI_Controller {
    function __construct() {
        parent::__construct();
        $this->load->model('Kriteria_model');
        $this->load->model('Subkriteria_model');
    } 

    /*
    * Listing of subkriteria
    */
    public function index() {
    try {
        $id_user = $this->session->userdata('id_user');
        $level = $this->session->userdata('level');
        $data['title'] = 'Subkriteria';
        $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
        $data['list_user'] = $this->db->get('mst_user')->result_array();
        $data['identitas'] = $this->db->get('tbl_aplikasi')->row();
        $data['level'] = $level;
        // Pastikan subkriteria selalu berupa array
        $subkriteria = $this->Subkriteria_model->get_all_with_asso_subkriteria();
        $data['subkriteria'] = is_array($subkriteria) ? $subkriteria : [];

        $this->load->view('templates/header', $data);
        if($level == 'Admin'){
                $this->load->view('templates/sidebar_admin', $data);
            }elseif($level == 'Perbekel'){
                $this->load->view('templates/sidebar_perbekel', $data);
            }

        $this->load->view('admin/subkriteria/index', $data);
        $this->load->view('templates/footer');
    } catch (Exception $ex) {
        throw new Exception('Subkriteria Controller : Error in index function - ' . $ex);
    }
}

    /*
    * Adding a new subkriteria
    */
    function add() {  
        try {
            $params = array(
                'id_kriteria' => $this->input->post('id_kriteria'),
                'nama_subkriteria' => $this->input->post('nama_subkriteria'),
                'nilai' => $this->input->post('nilai'),
            );
            $this->load->library('upload');
            $this->load->library('form_validation');
            $this->form_validation->set_rules('id_kriteria', 'Kriteria', 'required');
            $this->form_validation->set_rules('nama_subkriteria', 'Nama Subkriteria', 'required');
            $this->form_validation->set_rules('nilai', 'Nilai', 'required');
            if ($this->form_validation->run()) {  
                $id = $this->Subkriteria_model->add_subkriteria($params);
                $this->session->set_flashdata('msg','simpan');
                $this->session->set_flashdata('alert_msg', '<div class="alert alert-success text-center">Succesfully added.</div>');
                redirect('subkriteria/index');
            } else {
                $id_user = $this->session->userdata('id_user');
                $data['title'] = 'Tambah Subkriteria';
                $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
                $data['list_user'] = $this->db->get('mst_user')->result_array();
                $data['identitas'] = $this->db->get('tbl_aplikasi')->row();
                $data['all_kriteria'] = $this->Kriteria_model->get_all_kriteria(); 
                $this->load->view('templates/header', $data);
                $this->load->view('templates/sidebar_admin', $data);
                $this->load->view('admin/subkriteria/add', $data);
                $this->load->view('templates/footer');
            }
        } catch (Exception $ex) {
            throw new Exception('Subkriteria Controller : Error in add function - ' . $ex);
        }  
    }  

    /*
    * Editing a subkriteria
    */
    public function edit($id) {   
        try {
            $data['subkriteria'] = $this->Subkriteria_model->get_subkriteria($id);
            $this->load->library('upload');
            $this->load->library('form_validation');
            if (isset($data['subkriteria']['id'])) {
                $params = array(
                    'id_kriteria' => $this->input->post('id_kriteria'),
                    'nama_subkriteria' => $this->input->post('nama_subkriteria'),
                    'nilai' => $this->input->post('nilai'),
                );
                $this->form_validation->set_rules('id_kriteria', 'id_kriteria', 'required');
                $this->form_validation->set_rules('nama_subkriteria', 'nama_subkriteria', 'required');
                $this->form_validation->set_rules('nilai', 'nilai', 'required');
                if ($this->form_validation->run()) {  
                    $this->Subkriteria_model->update_subkriteria($id, $params);
                    $this->session->set_flashdata('msg','edit');
                    $this->session->set_flashdata('alert_msg', '<div class="alert alert-info text-center">Succesfully updated.</div>');
                    redirect('subkriteria/index');
                } else {
                    $id_user = $this->session->userdata('id_user');
                    $data['title'] = 'Edit Subkriteria';
                    $data['user'] = $this->db->get_where('mst_user', ['email' => $this->session->userdata('email')])->row_array();
                    $data['list_user'] = $this->db->get('mst_user')->result_array();
                    $data['identitas'] = $this->db->get('tbl_aplikasi')->row();
                    $data['all_kriteria'] = $this->Kriteria_model->get_all_kriteria(); 
                    $this->load->view('templates/header', $data);
                    $this->load->view('templates/sidebar_admin', $data);
                    $this->load->view('admin/subkriteria/edit', $data);
                    $this->load->view('templates/footer');
                }
            } else {
                show_error('The subkriteria you are trying to edit does not exist.');
            }
        } catch (Exception $ex) {
            throw new Exception('Subkriteria Controller : Error in edit function - ' . $ex);
        }  
    } 

    /*
    * Deleting subkriteria
    */
    function remove($id) {
        try {
            $subkriteria = $this->Subkriteria_model->get_subkriteria($id);
            // check if the subkriteria exists before trying to delete it
            if (isset($subkriteria['id'])) {
                $this->Subkriteria_model->delete_subkriteria($id);
                $this->session->set_flashdata('alert_msg', '<div class="alert alert-success text-center">Succesfully Removed.</div>');
                redirect('subkriteria/index');
            } else {
                show_error('The subkriteria you are trying to delete does not exist.');
            }
        } catch (Exception $ex) {
            throw new Exception('Subkriteria Controller : Error in remove function - ' . $ex);
        }  
    }

    /*
    * View more a subkriteria
    */
    public function view_more($id) {   
        try {
            $data['subkriteria'] = $this->Subkriteria_model->get_subkriteria($id);
            if (isset($data['subkriteria']['id'])) {
                $data['_view'] = 'subkriteria/view_more';
                $this->load->view('layouts/main', $data);
            } else {
                show_error('The subkriteria you are trying to view more does not exist.');
            }
        } catch (Exception $ex) {
            throw new Exception('Subkriteria Controller : Error in View more function - ' . $ex);
        }  
    } 

    /*
    * Listing of subkriteria
    */
    public function search_by_clm() {
        $column_name = $this->input->post('column_name');
        $value_id = $this->input->post('value_id');
        $data['noof_page'] = 0;
        $params = array();
        $data['subkriteria'] = $this->Subkriteria_model->get_all_with_asso_subkriteria_by_cat($column_name, $value_id);
        $data['_view'] = 'subkriteria/index';
        $this->load->view('layouts/main', $data);
    }

    /*
    * get get_search_values_byclms by id
    */
    public function get_search_values_by_id_kriteria() {   
        $id_kriteria = $this->input->post('value');
        $this->load->model('Kriteria_model');
        $data['all_kriteria'] = $this->Kriteria_model->get_all_kriteria(); 
        $subkriteria = $this->Subkriteria_model->get_all_with_asso_subkriteria();
        if (isset($data['all_kriteria']) && $data['all_kriteria'] != null) {
            foreach ($data['all_kriteria'] as $s) { 
                echo "<option value='".$s['id']."'> ".$s['nama_kriteria']."</option>"; 
            } 
        } else {
            echo '<tr>No data found</tr>';
        }
    } 

    /*
    * get search values by column- subkriteria
    */
    public function get_search_values_by_clm() {
        $clm_name = $this->input->post('clm_name');
        $value = $this->input->post('value');
        $id = $this->input->post('id');
        $params = array(
            $clm_name => $value,
        );
        $this->Subkriteria_model->update_subkriteria($id, $params);
        $data['noof_page'] = 0;
        $data['subkriteria'] = $this->Subkriteria_model->get_all_with_asso_subkriteria();
        $this->load->view('subkriteria/index', $data);
    }
}
