<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Alternatif_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      public function import_alternatif($data) {
        // Pastikan kolom sesuai dengan struktur tabel alternatif
        $this->db->insert_batch('alternatif', $data);
    }
      /*
        * Get alternatif by id 
      */ 
      function get_alternatif($id)
      {
        try{
           return $this->db->get_where('alternatif',array('id'=>$id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model Model : Error in get_alternatif function - ' . $ex);
           }  
      }
      /*
        * Get alternatif by  column name
      */ 
      function get_alternatifbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('alternatif',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model Madel : Error in get_alternatifbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All alternatif count 
      */ 
      function get_all_alternatif_count()
      {
        try{
           $this->db->from('alternatif');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in get_all_alternatif_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join alternatifcount 
      */ 
      function get_all_with_asso_alternatif()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in get_all_with_asso_alternatif function - ' . $ex);
           }  
      }
      /*
          * Get all alternatif 
      */ 
      function get_all_alternatif($params = array())
      {
        try{
              $this->db->order_by('id', 'asc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('alternatif')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in get_all_alternatif function - ' . $ex);
           }  
      } 
      /*
         * function to add new alternatif 
      */
      function add_alternatif($params)
      {
        try{
          $this->db->insert('alternatif',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in add_alternatif function - ' . $ex);
           }  
      }
      /* 
          * function to update alternatif 
      */
      function update_alternatif($id,$params)
      {
        try{
            $this->db->where('id',$id);
        return $this->db->update('alternatif',$params);
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in update_alternatif function - ' . $ex);
           }  
       }
     /* 
          * function to delete alternatif 
      */
       function delete_alternatif($id)
       {
        try{
             return $this->db->delete('alternatif',array('id'=>$id));
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in delete_alternatif function - ' . $ex);
           }  
       }
      /*
        * Get alternatif by  column name where not in particular id
      */ 
      function get_alternatifbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id!=', $where_cond);
           return $this->db->get_where('alternatif',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in get_alternatifbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join alternatifcount 
      */ 
      function get_all_with_asso_alternatif_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in get_all_with_asso_alternatif_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all alternatif_by_cat 
      */ 
      function get_all_alternatif_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('alternatif')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Alternatif_model model : Error in get_all_alternatif_by_cat function - ' . $ex);
           }  
      } 
 }