<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Kriteria_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      function get_all_kriteria_by_jenis()
      {
        try{
              $this->db->order_by('type', 'asc');
               return $this->db->get('kriteria')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in get_all_kriteria_by_jenis function - ' . $ex);
           }  
      }
      function get_all_kriteria_by_bobot() 
      {
          try {
              $this->db->order_by('bobot', 'asc');
              return $this->db->get('kriteria')->result_array();
          } catch (Exception $ex) {
              throw new Exception('Kriteria_model model : Error in get_all_kriteria_by_bobot function - ' . $ex);
          }
      }
      /*
        * Get kriteria by id 
      */ 
      function get_kriteria($id)
      {
        try{
           return $this->db->get_where('kriteria',array('id'=>$id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model Model : Error in get_kriteria function - ' . $ex);
           }  
      }
      /*
        * Get kriteria by  column name
      */ 
      function get_kriteriabyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('kriteria',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model Madel : Error in get_kriteriabyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All kriteria count 
      */ 
      function get_all_kriteria_count()
      {
        try{
           $this->db->from('kriteria');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in get_all_kriteria_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join kriteriacount 
      */ 
      function get_all_with_asso_kriteria()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in get_all_with_asso_kriteria function - ' . $ex);
           }  
      }
      /*
          * Get all kriteria 
      */ 
      function get_all_kriteria($params = array())
      {
        try{
              $this->db->order_by('id', 'asc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('kriteria')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in get_all_kriteria function - ' . $ex);
           }  
      } 
      /*
         * function to add new kriteria 
      */
      function add_kriteria($params)
      {
        try{
          $this->db->insert('kriteria',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in add_kriteria function - ' . $ex);
           }  
      }
      /* 
          * function to update kriteria 
      */
      function update_kriteria($id,$params)
      {
        try{
            $this->db->where('id',$id);
        return $this->db->update('kriteria',$params);
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in update_kriteria function - ' . $ex);
           }  
       }
     /* 
          * function to delete kriteria 
      */
       function delete_kriteria($id)
       {
        try{
             return $this->db->delete('kriteria',array('id'=>$id));
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in delete_kriteria function - ' . $ex);
           }  
       }
      /*
        * Get kriteria by  column name where not in particular id
      */ 
      function get_kriteriabyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id!=', $where_cond);
           return $this->db->get_where('kriteria',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in get_kriteriabyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join kriteriacount 
      */ 
      function get_all_with_asso_kriteria_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in get_all_with_asso_kriteria_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all kriteria_by_cat 
      */ 
      function get_all_kriteria_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('kriteria')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Kriteria_model model : Error in get_all_kriteria_by_cat function - ' . $ex);
           }  
      } 
 }