<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Subkriteria_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get subkriteria by id 
      */ 
      function get_all_subkriteria_by_kriteria($id_kriteria)
      {
        try{
           return $this->db->get_where('subkriteria',array('id_kriteria'=>$id_kriteria))->result_array();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model Model : Error in get_all_subkriteria_by_kriteria function - ' . $ex);
           }
      }
      function get_subkriteria($id)
      {
        try{
           return $this->db->get_where('subkriteria',array('id'=>$id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model Model : Error in get_subkriteria function - ' . $ex);
           }  
      }
      /*
        * Get subkriteria by  column name
      */ 
      function get_subkriteriabyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('subkriteria',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model Madel : Error in get_subkriteriabyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All subkriteria count 
      */ 
      function get_all_subkriteria_count()
      {
        try{
           $this->db->from('subkriteria');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in get_all_subkriteria_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join subkriteriacount 
      */ 
      function get_all_with_asso_subkriteria()
        {
            try {
                $this->db->select('a.*,b.nama_kriteria');
                $this->db->from('subkriteria a');
                $this->db->join('kriteria b', 'b.id = a.id_kriteria');
                $query = $this->db->get();

                if ($query->num_rows() > 0) {
                    return $query->result_array(); // Mengembalikan array hasil query
                } else {
                    return []; // Mengembalikan array kosong jika tidak ada data
                }
            } catch (Exception $ex) {
                throw new Exception('Subkriteria_model model : Error in get_all_with_asso_subkriteria function - ' . $ex);
            }
        }
      /*
          * Get all subkriteria 
      */ 
      function get_all_subkriteria($params = array())
      {
        try{
              $this->db->order_by('id', 'asc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('subkriteria')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in get_all_subkriteria function - ' . $ex);
           }  
      } 
      /*
         * function to add new subkriteria 
      */
      function add_subkriteria($params)
      {
        try{
          $this->db->insert('subkriteria',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in add_subkriteria function - ' . $ex);
           }  
      }
      /* 
          * function to update subkriteria 
      */
      function update_subkriteria($id,$params)
      {
        try{
            $this->db->where('id',$id);
        return $this->db->update('subkriteria',$params);
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in update_subkriteria function - ' . $ex);
           }  
       }
     /* 
          * function to delete subkriteria 
      */
       function delete_subkriteria($id)
       {
        try{
             return $this->db->delete('subkriteria',array('id'=>$id));
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in delete_subkriteria function - ' . $ex);
           }  
       }
      /*
        * Get subkriteria by  column name where not in particular id
      */ 
      function get_subkriteriabyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id!=', $where_cond);
           return $this->db->get_where('subkriteria',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in get_subkriteriabyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join subkriteriacount 
      */ 
      function get_all_with_asso_subkriteria_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('subkriteria a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('kriteria b', 'b.id=a. id_kriteria','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in get_all_with_asso_subkriteria_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all subkriteria_by_cat 
      */ 
      function get_all_subkriteria_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('subkriteria')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Subkriteria_model model : Error in get_all_subkriteria_by_cat function - ' . $ex);
           }  
      } 
 }